title: Task Craftr
email: olivier.patry@gmail.com
description: >-
  **Task Craftr** is an Android task management app built using Google Tasks API.
  Developed to demonstrate my expertise in modern Android development, it highlights my skills in architecture,
  UI design with Jetpack Compose, OAuth authentication, and more—all packaged in a sleek, user-friendly interface.
baseurl: '/task-craftr'
url: 'https://opatry.github.io'
twitter_username: o_patry
github_username:  opatry

markdown: kramdown
theme: jekyll-theme-basically-basic
