name: Build & Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        checks: write
        id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: ☕ Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: 🐘 Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        add-job-summary-as-pr-comment: on-failure

    - name: 🔨 Build Android App 📱
      env:
        PLAYSTORE_SECRET_PASSPHRASE: ${{ secrets.PLAYSTORE_SECRET_PASSPHRASE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      run: |
            set -eux
            ./_ci/decrypt_secrets.sh
            ./gradlew --no-daemon :tasks-app-android:assembleStoreRelease \
              -Pci=true \
              -Pplaystore.keystore.file="${PWD}/_ci/tasksApp.keystore" \
              -Pplaystore.keystore.password="${KEYSTORE_PASSWORD}" \
              -Pplaystore.keystore.key_password="${KEYSTORE_KEY_PASSWORD}"

    - name: 🔨 Build Desktop App 🖥️
      run: ./gradlew --no-daemon :tasks-app-desktop:assemble

    - name: ✅ Test
      run: ./gradlew --no-daemon test

    - name: 🗒️ Publish Test Reports
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
