name: 🚀 Play Store publish
on:
  workflow_dispatch:

jobs:
   build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: ☕ Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: 🐘 Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        add-job-summary-as-pr-comment: on-failure
